spring.application.name=tradeconnect

# 1.1. Server Port Configuration
server.port=5555

# 1.2. Application Context Path Configuration
server.servlet.context-path=/tradeconnect

# 1.4 & 1.5. OpenAPI and Swagger UI Custom Path Configurations
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# H2 in-memory database configuration for local execution
spring.datasource.url=jdbc:h2:mem:tradeconnectdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true